# Generated by Django 3.0.4 on 2020-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=4)),
                ('weight', models.CharField(max_length=3)),
                ('diagnosis', models.CharField(max_length=1220)),
                ('address', models.CharField(max_length=12222)),
                ('medicalhistory', models.CharField(max_length=12222)),
                ('date', models.DateField()),
            ],
        ),
    ]
