# Generated by Django 3.0.4 on 2020-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_existpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpatient',
            name='id',
        ),
        migrations.AddField(
            model_name='newpatient',
            name='yourid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
