# Generated by Django 3.0.4 on 2020-08-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200827_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='existpatient',
            name='patientid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='yourid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
