# Generated by Django 3.0.4 on 2020-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200831_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existpatient',
            name='footbottom',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='foottop',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='handsback',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='handsfront',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='lefteye',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='legs',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='pulse',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='righteye',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='roomhumidity',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='roomtemperature',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='existpatient',
            name='weight',
            field=models.CharField(max_length=122),
        ),
    ]
