# Generated by Django 3.0.4 on 2020-09-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200901_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(default='', max_length=10)),
                ('bpsys', models.CharField(max_length=22)),
                ('bpdia', models.CharField(max_length=22)),
                ('visceralfatlevel', models.CharField(max_length=122)),
                ('restingmetabolism', models.CharField(max_length=122)),
                ('bmi', models.CharField(max_length=122)),
                ('bfp', models.CharField(max_length=122)),
                ('bodytemperature', models.CharField(max_length=122)),
                ('skeletalmusclepercentage', models.CharField(max_length=122)),
                ('footbottom', models.ImageField(default='', upload_to='home/images')),
                ('foottop', models.ImageField(default='', upload_to='home/images')),
                ('legs', models.ImageField(default='', upload_to='home/images')),
                ('handsfront', models.ImageField(default='', upload_to='home/images')),
                ('handsback', models.ImageField(default='', upload_to='home/images')),
                ('lefteye', models.ImageField(default='', upload_to='home/images')),
                ('righteye', models.ImageField(default='', upload_to='home/images')),
                ('pulse', models.CharField(max_length=122)),
                ('weight', models.CharField(max_length=122)),
                ('roomhumidity', models.CharField(max_length=122)),
                ('roomtemperature', models.CharField(max_length=122)),
            ],
        ),
    ]
