# Generated by Django 3.0.4 on 2020-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='machineid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
