# Generated by Django 3.0.4 on 2020-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_live_machineid'),
    ]

    operations = [
        migrations.AddField(
            model_name='existpatient',
            name='glucoselevel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
