# Generated by Django 3.0.4 on 2020-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_existpatient_glucoselevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpatient',
            name='medicalhistory',
        ),
        migrations.AddField(
            model_name='newpatient',
            name='allergic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='almosteveryday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='anginapectoris',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='congesticcardiacfailure',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='daily',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='diabetes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='everyday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='everyday1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='everyday2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='heartproblem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='hospitalization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='hypertension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='medication',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='never',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='never1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='never2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='never3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='never4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='once',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='onetotwodays',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='onetotwodays1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='onetotwodays2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='rarely',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='sometimes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='surgery',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='threetosixdays',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='threetosixdays1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='threetosixdays2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='thyroid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='tobacco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='twotothreetimes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
